// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9RnHWDaXgrNWKvntO8c1XbwNWSH0U7Q',
    appId: '1:947029214867:web:0b5f17ed856c640deeef66',
    messagingSenderId: '947029214867',
    projectId: 'merc-mania',
    authDomain: 'merc-mania.firebaseapp.com',
    storageBucket: 'merc-mania.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9H-TQREb6M7SDgClC0b9nS_RSURAypfY',
    appId: '1:947029214867:android:0dd316292718dd71eeef66',
    messagingSenderId: '947029214867',
    projectId: 'merc-mania',
    storageBucket: 'merc-mania.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfBxokvSmVzi959udM4z-LblfBgms2d7s',
    appId: '1:947029214867:ios:343c4f67d084a845eeef66',
    messagingSenderId: '947029214867',
    projectId: 'merc-mania',
    storageBucket: 'merc-mania.appspot.com',
    androidClientId: '947029214867-d6tblqq61r2i6ig9ksgl4ms3odp1tldn.apps.googleusercontent.com',
    iosClientId: '947029214867-cs6vptbsu382lucpjk1v9dtd8fnia34h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mercMania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfBxokvSmVzi959udM4z-LblfBgms2d7s',
    appId: '1:947029214867:ios:343c4f67d084a845eeef66',
    messagingSenderId: '947029214867',
    projectId: 'merc-mania',
    storageBucket: 'merc-mania.appspot.com',
    androidClientId: '947029214867-d6tblqq61r2i6ig9ksgl4ms3odp1tldn.apps.googleusercontent.com',
    iosClientId: '947029214867-cs6vptbsu382lucpjk1v9dtd8fnia34h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mercMania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa9RnHWDaXgrNWKvntO8c1XbwNWSH0U7Q',
    appId: '1:947029214867:web:bfbb90499360b2afeeef66',
    messagingSenderId: '947029214867',
    projectId: 'merc-mania',
    authDomain: 'merc-mania.firebaseapp.com',
    storageBucket: 'merc-mania.appspot.com',
  );

}