// ignore_for_file: avoid_print

import 'package:cloud_firestore/cloud_firestore.dart';

class OrderService {
  FirebaseFirestore firestore = FirebaseFirestore.instance;
  final orderCollectionRef = FirebaseFirestore.instance.collection('orders');


/// Create new Order
  Future<void> createOrder(Map<String, dynamic> data) async {
    try {
      final docRef = await orderCollectionRef.add(data);
      print('Data added successfully');
      final autoGeneratedId = docRef.id;
      await docRef.update({'id' : autoGeneratedId});
      print('Update id successfully');
    } catch (e) {
      print('$e');
    }
  }
  
  /// Get all Orders
  Future<QuerySnapshot<Map<String, dynamic>>> getAppOrders(String id) {
    return orderCollectionRef.where('user_id', isEqualTo: id).get();
  }
}